# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='admin.proto',
  package='admin',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61\x64min.proto\x12\x05\x61\x64min\"5\n\x0c\x45ventRequest\x12\x14\n\x0cjson_request\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"<\n\rEventResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\x05\"\x13\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\x05\"\"\n\tEventData\x12\x15\n\rjson_response\x18\x01 \x01(\t\"\x06\n\x04NULL\"\x18\n\x08\x43ityJSON\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"\x16\n\x07TagJSON\x12\x0b\n\x03tag\x18\x01 \x01(\t\"\x12\n\x03URL\x12\x0b\n\x03url\x18\x01 \x01(\t\"2\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t2\x88\x02\n\x0c\x41\x64minHandler\x12;\n\x0cinsert_event\x12\x13.admin.EventRequest\x1a\x14.admin.EventResponse\"\x00\x12\x31\n\rdisplay_event\x12\x0c.admin.Event\x1a\x10.admin.EventData\"\x00\x12\x32\n\x10get_all_province\x12\x0b.admin.NULL\x1a\x0f.admin.CityJSON\"\x00\x12,\n\x0bget_all_tag\x12\x0b.admin.NULL\x1a\x0e.admin.TagJSON\"\x00\x12&\n\x08save_img\x12\n.admin.URL\x1a\x0c.admin.Image\"\x00\x62\x06proto3')
)




_EVENTREQUEST = _descriptor.Descriptor(
  name='EventRequest',
  full_name='admin.EventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_request', full_name='admin.EventRequest.json_request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='admin.EventRequest.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=75,
)


_EVENTRESPONSE = _descriptor.Descriptor(
  name='EventResponse',
  full_name='admin.EventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='admin.EventResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='admin.EventResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='admin.EventResponse.event_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=137,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='admin.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='admin.Event.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=158,
)


_EVENTDATA = _descriptor.Descriptor(
  name='EventData',
  full_name='admin.EventData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_response', full_name='admin.EventData.json_response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=194,
)


_NULL = _descriptor.Descriptor(
  name='NULL',
  full_name='admin.NULL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=202,
)


_CITYJSON = _descriptor.Descriptor(
  name='CityJSON',
  full_name='admin.CityJSON',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='admin.CityJSON.city', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=228,
)


_TAGJSON = _descriptor.Descriptor(
  name='TagJSON',
  full_name='admin.TagJSON',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='admin.TagJSON.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=252,
)


_URL = _descriptor.Descriptor(
  name='URL',
  full_name='admin.URL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='admin.URL.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=272,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='admin.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='admin.Image.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='admin.Image.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='admin.Image.filename', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=324,
)

DESCRIPTOR.message_types_by_name['EventRequest'] = _EVENTREQUEST
DESCRIPTOR.message_types_by_name['EventResponse'] = _EVENTRESPONSE
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['EventData'] = _EVENTDATA
DESCRIPTOR.message_types_by_name['NULL'] = _NULL
DESCRIPTOR.message_types_by_name['CityJSON'] = _CITYJSON
DESCRIPTOR.message_types_by_name['TagJSON'] = _TAGJSON
DESCRIPTOR.message_types_by_name['URL'] = _URL
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventRequest = _reflection.GeneratedProtocolMessageType('EventRequest', (_message.Message,), dict(
  DESCRIPTOR = _EVENTREQUEST,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:admin.EventRequest)
  ))
_sym_db.RegisterMessage(EventRequest)

EventResponse = _reflection.GeneratedProtocolMessageType('EventResponse', (_message.Message,), dict(
  DESCRIPTOR = _EVENTRESPONSE,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:admin.EventResponse)
  ))
_sym_db.RegisterMessage(EventResponse)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:admin.Event)
  ))
_sym_db.RegisterMessage(Event)

EventData = _reflection.GeneratedProtocolMessageType('EventData', (_message.Message,), dict(
  DESCRIPTOR = _EVENTDATA,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:admin.EventData)
  ))
_sym_db.RegisterMessage(EventData)

NULL = _reflection.GeneratedProtocolMessageType('NULL', (_message.Message,), dict(
  DESCRIPTOR = _NULL,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:admin.NULL)
  ))
_sym_db.RegisterMessage(NULL)

CityJSON = _reflection.GeneratedProtocolMessageType('CityJSON', (_message.Message,), dict(
  DESCRIPTOR = _CITYJSON,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:admin.CityJSON)
  ))
_sym_db.RegisterMessage(CityJSON)

TagJSON = _reflection.GeneratedProtocolMessageType('TagJSON', (_message.Message,), dict(
  DESCRIPTOR = _TAGJSON,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:admin.TagJSON)
  ))
_sym_db.RegisterMessage(TagJSON)

URL = _reflection.GeneratedProtocolMessageType('URL', (_message.Message,), dict(
  DESCRIPTOR = _URL,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:admin.URL)
  ))
_sym_db.RegisterMessage(URL)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'admin_pb2'
  # @@protoc_insertion_point(class_scope:admin.Image)
  ))
_sym_db.RegisterMessage(Image)



_ADMINHANDLER = _descriptor.ServiceDescriptor(
  name='AdminHandler',
  full_name='admin.AdminHandler',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=327,
  serialized_end=591,
  methods=[
  _descriptor.MethodDescriptor(
    name='insert_event',
    full_name='admin.AdminHandler.insert_event',
    index=0,
    containing_service=None,
    input_type=_EVENTREQUEST,
    output_type=_EVENTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='display_event',
    full_name='admin.AdminHandler.display_event',
    index=1,
    containing_service=None,
    input_type=_EVENT,
    output_type=_EVENTDATA,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_all_province',
    full_name='admin.AdminHandler.get_all_province',
    index=2,
    containing_service=None,
    input_type=_NULL,
    output_type=_CITYJSON,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_all_tag',
    full_name='admin.AdminHandler.get_all_tag',
    index=3,
    containing_service=None,
    input_type=_NULL,
    output_type=_TAGJSON,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='save_img',
    full_name='admin.AdminHandler.save_img',
    index=4,
    containing_service=None,
    input_type=_URL,
    output_type=_IMAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADMINHANDLER)

DESCRIPTOR.services_by_name['AdminHandler'] = _ADMINHANDLER

# @@protoc_insertion_point(module_scope)
