# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import admin_pb2 as admin__pb2


class AdminHandlerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.insert_event = channel.unary_unary(
        '/admin.AdminHandler/insert_event',
        request_serializer=admin__pb2.EventRequest.SerializeToString,
        response_deserializer=admin__pb2.EventResponse.FromString,
        )
    self.display_event = channel.unary_unary(
        '/admin.AdminHandler/display_event',
        request_serializer=admin__pb2.Event.SerializeToString,
        response_deserializer=admin__pb2.EventData.FromString,
        )
    self.get_all_province = channel.unary_unary(
        '/admin.AdminHandler/get_all_province',
        request_serializer=admin__pb2.NULL.SerializeToString,
        response_deserializer=admin__pb2.CityJSON.FromString,
        )
    self.get_all_tag = channel.unary_unary(
        '/admin.AdminHandler/get_all_tag',
        request_serializer=admin__pb2.NULL.SerializeToString,
        response_deserializer=admin__pb2.TagJSON.FromString,
        )
    self.save_img = channel.unary_unary(
        '/admin.AdminHandler/save_img',
        request_serializer=admin__pb2.URL.SerializeToString,
        response_deserializer=admin__pb2.Image.FromString,
        )


class AdminHandlerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def insert_event(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def display_event(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_all_province(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_all_tag(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def save_img(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdminHandlerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'insert_event': grpc.unary_unary_rpc_method_handler(
          servicer.insert_event,
          request_deserializer=admin__pb2.EventRequest.FromString,
          response_serializer=admin__pb2.EventResponse.SerializeToString,
      ),
      'display_event': grpc.unary_unary_rpc_method_handler(
          servicer.display_event,
          request_deserializer=admin__pb2.Event.FromString,
          response_serializer=admin__pb2.EventData.SerializeToString,
      ),
      'get_all_province': grpc.unary_unary_rpc_method_handler(
          servicer.get_all_province,
          request_deserializer=admin__pb2.NULL.FromString,
          response_serializer=admin__pb2.CityJSON.SerializeToString,
      ),
      'get_all_tag': grpc.unary_unary_rpc_method_handler(
          servicer.get_all_tag,
          request_deserializer=admin__pb2.NULL.FromString,
          response_serializer=admin__pb2.TagJSON.SerializeToString,
      ),
      'save_img': grpc.unary_unary_rpc_method_handler(
          servicer.save_img,
          request_deserializer=admin__pb2.URL.FromString,
          response_serializer=admin__pb2.Image.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'admin.AdminHandler', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
